mainfolder/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtfforms import StringField, SubmitField, TextAreaField
from wtf.validators import DataRequirered

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequirered()])
    text = TextAreaField('Text', validators = [DataRequirered()])
    submit = SubmitField("Post")
    #ksdbfksdjhfkj

mainfolder/blog_posts/views.py
#blog_post/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from mainfolder import db
from mainfolder.models import BlogPost
from mainfolder.blog_posts import BlogPostForm

blog_post = Bluerint('blog_post', __name__)

# CREATE
@blog_post.route('/create', methods = ['GET', 'POST'])
@login_required
def create_post ():
    form = BlogPost()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash ('Blog Post Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html', form =form)

# BLOG POST (VIEW)
@blog_post.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post= BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title,
    date=blog_post.date, post=blog_post)

# UPDATE
@blog_post.route('/<int:blog_post_id/update', methods= ['GET','POST'])
@login_required
def update(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        aborth(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data

        flash('Blog Post Updated')
        return redirect(url_for('blog_post.blog_post'), blog_post_id = blog_post_id)

    elif request.method = 'GET':

        form.text.data = blog_post.text
        form.title.data = blog_post.title

    return render_template('create_post.html', title ='Updating', form =form)

# DELETE
@blog_post.route('/<int:blog_post_id/delete', methods = ['GET', 'POST'])
@login_required

def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        aborth(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')

    return redirect(url_for('core.index'))
    

mainfolder/core/views.py
#core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    #more to fill
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

mainfolder/users/views.py
#users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user,logout_user, login_required
from mainfolder import db
from mainfolder.models import User, BlogPost
from mainfolder.users.forms import RegistrationForm, LoginForm, UpdateUserFormm
from mainfolder.users.picture_handler import add_profile_pic
import time

users = Blueprint('users', __name__)

#register
@users.route("/register", methods=["GET", "POST"])
def register():
    form= RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data,
            password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash("Thaks for registration !")
        time.sleep(5)
        return redirect(url_for("users.login"))
    return render_template("register.html", form = form)


#login
@users.route("/login", methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login Success !")
            time.sleep(3)

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template("login.html", form = form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

#acount(update UserForm)
@users.route('/account', methods= ['GET', 'POST'])
@login_required
def account():

    form = UpdateUserFormm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic
            #this is just a string :)))

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        #flash('Users Account Updated !')
        #time.sleep(3)
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename= 'profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image = profile_image, form = form)





#user's list of Blog post
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1, type = int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_post = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html', blog_post=blog_post, user=user)

mainfolder/templates/account.html
{%  extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <div align="center">
    <h1>Welcom to the page for {{current_user.username}}</h1>
    <img align="center" src="{{url_for('static', filename = 'profile_pics/'+current_user.profile_image)}}"style="width:150px">
  </div>

</div>

<div class="container">
  <form method="POST">
  {{form.hidden_tag()}}
  <div class="form-group">
    {{form.username.label(class="form-group")}}
    {{form.username(class="form-control")}}
  </div>

  <div class="form-group">
    {{form.email.label(class="form-group")}}
    {{form.email(class="form-control")}}
  </div>

  <div class="form-group">
    {{form.picture.label(class="form-group")}}
    {{form.picture(class="form-control")}}
  </div>

  <div class="form-group">
    {{form.submit(class="btn btn-primary")}}
  </div>

  </form>

</div>

{% endblock %}

mainfolder/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title>This Social APP!</title>
  </head>
  <style>
img {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
}

img:hover {
  box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
}
</style>
  <body>
    <ul class="nav">
      <li class="nav-link">
        <a href="{{url_for('core.index')}}">Home</a>
      </li>
      <br>
      <li class="nav-link">
        <a href="{{url_for('core.info')}}">About</a>
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-link">
        <a href="{{url_for('users.logout')}}">Logout</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for('users.account')}}">Acount</a>
      </li>
      <li class="nav-link">
        <a href="#">Create Post</a>
      </li>
      {% else %}
      <li class="nav-link">
        <a href="{{url_for('users.login')}}">Log In</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for('users.register')}}">Register</a>
      </li>

    </ul>
      {% endif %}

    <div class="container">
    {% block content %}

    {% endblock %}

    </div>

  </body>
</html>

mainfolder/templates/blog_post.html
{% extends "base.html"%}

{% block content %}
<div class="jumbotron">
  <h1>{{post.title}}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{post.date.strftime('B% %d, %Y')}}</h3>


  <p>{{post.text}}</p>

  {% if post.author == current_user %}
    <div>
      <a href="{{url_for('blog_posts.update', blog_post_id= post.id)}}">Update</a>
      <button type="button" class="btn btn-danger"  data-toggle='modal' data-taget="#del_modal">Delte</button>
    </div>
    {% endif %}
  </div>

  <div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Modal body text goes here.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
    </div>
{%endblock%}

mainfolder/templates/create_post.html
{% extends "base.html0" %}

{% block content %}

<div class="container">
  <form class="form-group" method="POST">
    {{form.hidden{_tag()}}}

    <div class="form-group">
      {{form.title.lable(class="form-control-lable")}}
      {{form.title(class="form-control form-control-lg")}}
    </div>

    <div class="form-group">
      {{form.text.lable(class="form-control-lable")}}
      {{form.text(class="form-control form-control-lg")}}

    </div>

    <div class="form-group">
      {{form.submit(class="btn btn-outline-info")}}

    </div>

  </form>

</div>

{%endblock%}

mainfolder/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>"X" Company Blog</h1>
  {% if current_user.is_authenticated %}
  <hr>
  <h2 class="alert alert-success" role="alert">Welcome back  dear {{current_user.username}}! </h2>
  <hr>
  {%endif%}
</div>

{% endblock %}

mainfolder/templates/info.html
{% extends "base.html"  %}
{% block content %}
<div class="jumbotron">
<h1>Info About Our Company.</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem doloremque magnam a
   sint tempora quibusdam architecto. Laboriosam expedita impedit quibusdam, excepturi totam
    eos voluptates numquam blanditiis dolorum. Nulla, quod assumenda.</p>

</div>

{% endblock %}

mainfolder/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
  <div class="form-group">
  {{form.hidden_tag()}}
  {{form.email.label}}<br>{{form.email(class="email")}}
  <small id="emailHelp" class="form-text text-muted">Type your email address.</small><br>
  {{form.password.label}}<br>{{form.password}}<br>
  <small id="emailHelp" class="form-text text-muted">Type your password.</small><br>
  {{form.submit()}}

  </div>
</form>


{% endblock %}

mainfolder/templates/register.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
  <div class="form-group">
    <div class="container">


  {{form.hidden_tag()}}
  {{form.email.label}} <br>
  {{form.email(class="email", align = "center")}}
  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  <br>
  {{form.username.label}} <br>{{form.username(align = "center")}}<br>
  <small id="usernameHelp" class="form-text text-muted">Try unique username ..as need to not be in out database .</small>
  <br>
  {{form.password.label}} <br>{{form.password}}<br>
  <small id="passHelp" class="form-text text-muted">Try unique password ..as need to not be in out database .</small>

  {{form.pass_confirm.label}}<br>{{form.pass_confirm}}<br>
  <small id="passHelp" class="form-text text-muted">Repeat the unique password ..as need to not be in out database .</small>

  <br>
  {{form.submit()}}

    </div>
  </div>
</form>


{% endblock %}

mainfolder/templates/user_blog_posts.html
{%  extends "base.html" %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <div align="center">
      <h1>Welcome to the page for {{user.username}}</h1>
      <img src="{{url_for('static', filename ='profile_pics/'+user.profile_image )}}" >
    </div>
  </div>

{% for post in blog_post.items %}
<h2> <a href="{{url_for('blog_posts.blog_post', blog_post_id = post.id)}}">{{post.title}}</a></h2>
  Written By : <a href="{{url_for('users.user_post', username = post.author.username)}}">{{post.author.username }} </a>
  <p class="text-muted">Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
  <br>
  <p>{{post.text}}</p>
  <br>
{% endfor %}
</div>

<nav area-lable = "Page Navigation example">
  <ul class="pagination justify-content-center">
  {% for page_num in blog_posts.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
    {% if blog_post.page == page_num %}
    <li class="page-item disabled">
      <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}" >{{page_num}}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="{{url_for('users.user_posts', username= user.username, page= page_num)}}">{{page_num}}</a>
    </li>
    {% endif %}
  {% endfor %}

  </ul>

</nav>

{% endblock %}